import Header from "./components/Header";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";

const nunitoSans = Nunito_Sans(
  { subsets: ["latin"] },
  { weight: ["300", "600", "800"] }
);

export const metadata = {
  title: "Rest Countries API",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nunitoSans.variable} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
